load("//modules/adaptive_autosar/ara-api/log/test:test.bzl", "ap_log_test")

ap_log_test(
    name = "common_test",
)

ap_log_test(
    name = "func_test",
)

ap_log_test(
    name = "initial_test",
)

ap_log_test(
    name = "log_test",
)

ap_log_test(
    name = "utility_test",
)
