load("//modules/adaptive_autosar/ara-api/common:common_test.bzl", "ap_common_test")

ap_common_test(
    name = "test_ipc_message",
)

ap_common_test(
    name = "test_connect",
)

ap_common_test(
    name = "test_reconnect",
)

ap_common_test(
    name = "test_communication",
)
