load("//modules/adaptive_autosar/ara-api/common:common_test.bzl", "ap_common_test")

ap_common_test(
    name = "socket_test",
)

ap_common_test(
    name = "udp_test",
)

ap_common_test(
    name = "util_test",
)

ap_common_test(
    name = "buffer_test",
)
