load("//modules/adaptive_autosar/ara-api/core/test:test.bzl", "ap_core_test")

ap_core_test(
    name = "array_test",
)

ap_core_test(
    name = "instance_specifier_test",
)

ap_core_test(
    name = "core_error_domain_test",
)

ap_core_test(
    name = "error_code_test",
)

ap_core_test(
    name = "function_test",
)

ap_core_test(
    name = "future_error_domain_test",
)

ap_core_test(
    name = "map_test",
)

ap_core_test(
    name = "optional_test",
)

ap_core_test(
    name = "promise_test",
)

ap_core_test(
    name = "result_test",
)

ap_core_test(
    name = "string_test",
)

ap_core_test(
    name = "string_view_test",
)

ap_core_test(
    name = "abort_test",
)

ap_core_test(
    name = "vector_test",
)

ap_core_test(
    name = "variant_test",
)

ap_core_test(
    name = "condition_variable_test",
)

